### ISSUE TITLE
Setting height of a window through the argument object

### ISSUE THREAD

**Issue by Razip** [Nycto/PicoModal#13]
Can you add it? I mean:
```javascript
picoModal({content: 'some content', height: 300});
```
When a content bigger than a window's size there'll be a scrollbar. How about this?

**Comment by Nycto** [comment]
For anyone else that stumbles on this ticket: You should be able to accomplish this by setting the height in the `modalStyles` property, like this:

```javascript
var modal = picoModal({
    content: "Ah, the pitter patter of tiny feet in huge combat boots.<br>",
    modalStyles: function (styles) {
        styles.height = '200px';
    }
});

modal.show();
```
