### ISSUE TITLE
Make library compatible with npm/browserify

### ISSUE THREAD

**Issue by riggerthegeek** [Nycto/PicoModal#16]
This package is in npm yet is entirely incompatible with it.  It either needs an `index.js` file that links to `src/picoModal` or a main element in the package.json that does that same.

Also, the UMD that the file is wrapped in works great with AMD but not with Node or Browserify.  Check out https://github.com/umdjs/umd/blob/master/returnExports.js as I think this is the one you want (keeps working with window and AMD and adds in Browserify support).

Disappointing as think library is exactly what I need

**Comment by Nycto** [comment]
I can't remember why this never happened, but I would certainly support it. I noticed you forked; are you planning on submitting a pull request?

**Comment by riggerthegeek** [comment]
I thought it would originally be a case of just adding it into the package.json but it would require a rewrite of the code base too.

I know it's a flakey response, but it'll be a case that I do it by next weekend or not at all.  Deadlines and whatnot

**Comment by Nycto** [comment]
It shouldn't require too much rewriting; just swapping out the wrapping code. I should be able to whip something up in a few minutes...
