### ISSUE TITLE
Ok/Cancel dialog option

### ISSUE THREAD

**Issue by El4a** [Nycto/PicoModal#23]
It hoped for the modal to have a callback function for 'success' (user clicked ok) and a different callback for cancel (user does not want to continue with the action). Much like in the native js dialog box. Would it be possible to do this?

**Comment by Nycto** [comment]
I have intentionally left this kind of functionality out. My goal is to make it simple to implement this kind of functionality in the app layer, without burdening the library with a bunch of special cases.

But I think we can make it easier by allowing data to be passed to event handlers. For example, a user should be able to do this:

```javascript
function dialog(opts) {
    opts.content = "<p>" + opts.content + "</p>" +
        "<p><button class='cancel'>Cancel</button> <button class='ok'>Ok</button></p>";
    return picoModal(opts)
        .afterCreate(modal => {
            modal.modalElem().addEventListener("click", evt => {
                if (evt.target && evt.target.matches(".ok")) {
                    modal.close(true);
                } else if (evt.target && evt.target.matches(".cancel")) {
                    modal.close();
                }
            });
        })
        .afterClose((modal, event, success) => {
            var fn = success ? opts.onOk : opts.onCancel;
            fn && fn();
        });
}

dialog({
    content: "Ah, the pitter patter of tiny feet in huge combat boots.",
    onOk: () => console.log("ok!"),
    onCancel: () => console.log("cancelled")
}).show();
```

Notice the extra argument to `modal.close` above; that isn't currently possible. But it should be easy to implement.

**Comment by Nycto** [comment]
Here is an example of what it would look like to create an `ok/cancel` dialog with the changes I just pushed:

http://jsfiddle.net/h43dp9uy/

Very similar to what I sketched out above.

**Comment by El4a** [comment]
You are amazing! I've been trying to do it myself but that didn't go so well :p Thanks very much!
