### ISSUE TITLE
Modal isn't centered in mobie devices

### ISSUE THREAD

**Issue by NIBOGO** [Nycto/PicoModal#5]
If you try to open a modal in a mobile device or a table the modal isn't shown property.

**Comment by Nycto** [comment]
I've done a fairly large rewrite since this issue was originally filed; Looks like 23f5ca702a1dbdf2a8da14133e608228448fcfb5 is what was on mainline when this ticket was issued.

Let me know if this is still a problem. I did some quick testing on my iPhone and everything seems to work okay.

**Comment by Nycto** [comment]
Resolving. Feel free to reopen if this is still an issue
