### ISSUE TITLE
Close button does not works in IE9,10

### ISSUE THREAD

**Issue by gserg** [Nycto/PicoModal#9]
Internet Explorer 9 and 10 supports both attachEvent and addEventListener handlers
http://msdn.microsoft.com/en-us/library/ie/ms536343%28v=vs.85%29.aspx
http://msdn.microsoft.com/en-us/library/ie/ff975245%28v=vs.85%29.aspx

But IE9,10 Event object has no target property, so if you want to use attachEvent you need to use also event.srcElement instead of event.target

**Comment by Nycto** [comment]
Closed by 1e039b3 a while back. This ticket just never got resolved.

**Comment by marclawson3** [comment]
I am actually having this issue right now with IE 9.  The close button doesn't fire for me.

This snippet will reproduce:
```html
<div>
    <button id="mah-button" type="button">Show Lightbox</button>    
</div>
<script src="js/picoModal.min.js"></script>
<script>
    document.getElementById('mah-button').onclick = function() {
        picoModal("Ah, the pitter patter of tiny feet in huge combat boots.").show();
    }
</script>
```

**Comment by marclawson3** [comment]
I got the latest source (instead of the release) and re-tested with IE 9/10 and all is good.  Sorry for the worthless comment!

**Comment by Nycto** [comment]
Heads up: I bumped the version number and published an official release.
